name: UvaroDraft
author: Robert Syme
version: 0.0.1
description: A sample Polymer application
dependencies:
  polymer: any
  region_selector: 0.0.5
transformers:
- polymer:
    entry_points: web/uvarodraft.html
